apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-user
  namespace: web
subjects:
- kind: User
  name: webdev@msftopenhack6954ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: web-editor # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-user
  namespace: api
subjects:
- kind: User
  name: webdev@msftopenhack6954ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: api-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-user
  namespace: api
subjects:
- kind: User
  name: apidev@msftopenhack6954ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: api-editor # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-user
  namespace: web
subjects:
- kind: User
  name: apidev@msftopenhack6954ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: web-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io